### ISSUE TITLE
no need to create seek cues if the intent is to use MSE

### ISSUE THREAD

**Issue by jyavenard** [guest271314/MediaFragmentRecorder#4]
https://github.com/guest271314/recordMediaFragments/blob/a6e2856678a0e65fd4420042e196798e89a76c43/demos/recordMediaFragments.html#L169

MSE doesn't use nor need to seek cues set in a webm.

So creating a seek table when the intent is just to add the segments with MSE is unecessary,

**Comment by guest271314** [comment]
@jyavenard Media playback stalls at Chromium at `waiting` event of `HTMLVideoElement` if seek cues are not set when using `multipleUrls` at https://github.com/guest271314/recordMediaFragments/blob/a6e2856678a0e65fd4420042e196798e89a76c43/demos/recordMediaFragments.html#L169 that are `.mp4`.

**Comment by guest271314** [comment]
@jyavenard Good point. Expected result is rendered without using `ts-ebml-min.js`.

**Comment by guest271314** [comment]
@jyavenard Media playback stalls and `waiting` event is dispatched at `HTMLVideoElement` when media resource is `.mp4` file. `MediaSource.duration` logs `Infinity` at `timeupdate` event of `HTMLVideoElement`.

**Comment by guest271314** [comment]
@jyavenard Finally got what you mean relevant to usage of `"segments"` mode and `timestampOffset`.  Closing this issue.
